# Generated by Django 4.0.5 on 2022-06-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_theme_blog_is_public_blog_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='cover_img/'),
        ),
    ]
